version: '2.18.1'

services:

  core:
    container_name: cellenium-core
    volumes:
      - '/core:/app/core'
    build:
      context: /core

  tests:
    container_name: cellenium_core
    volumes:
      - '/tests:/app/tests'
    build:
      context: /test
    depends_on:
      - core
