version: '3'
services:

  core:
    volumes:
      - '/core:/app/core'
    build:
      context: /core/

  tests:
    volumes:
      - '/tests:/app/tests'
    build:
      context: /test/


  app:
    command: pytest
    restart: always
    depends_on:
      - core
      - tests
