version: '3'
services:

#  firefox:
#    image: selenium/node-firefox:latest
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - hub
#    environment:
#      HUB_HOST: hub
#    restart: always

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    restart: always

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
